blog/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.blog_list,name="blog_list"),
    path("<int:blog_pk>",views.blog_detail,name="blog_detail"),
    path("type/<int:blog_type_pk>",views.blogs_with_type,name="blogs_with_type"),
    path("date/<int:year>/<int:month>/<int:day>",views.blogs_with_date,name="blogs_with_date"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('', home, name="home"),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')), # 富文本编辑器上传图片配置
    path('blog/', include("blog.urls")),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.contenttypes.models import ContentType

from django.db import models
from django.db.models.fields import exceptions
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

from read_statistics.models import ReadNumExtendMethod


class BlogType(models.Model):
    title = models.CharField(max_length=32)
    def __str__(self):
        return self.title

class Blog(models.Model,ReadNumExtendMethod):
    """
    继承了read_statistics.models中的ReadNumExtendMethod
    获得get_read_num方法，可在admin中直接使用显示在后台
    """
    title = models.CharField(max_length=32)
    blog_type = models.ForeignKey(BlogType, on_delete=models.DO_NOTHING)
    content = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    # read_times = models.IntegerField(default=0)
    created_time = models.DateTimeField(auto_now_add=True)
    last_update_time = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title
    class Meta:
        ordering=['-created_time']

read_statistics/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.fields import exceptions
from django.utils import timezone


class ReadNum(models.Model):
    """
    统计每个模型对应数据的总共阅读数量
    """
    read_num = models.IntegerField(default=0)

    content_type = models.ForeignKey(ContentType, on_delete=models.DO_NOTHING) # 模型类
    object_id = models.PositiveIntegerField() # 模型类的具体对象
    content_object = GenericForeignKey("content_type", "object_id")


class ReadNumExtendMethod():
    """
    获取继承此类的子类的实例的总共阅读量
    """
    def get_read_num(self):
        ct = ContentType.objects.get_for_model(self)
        try:
            readnum = ReadNum.objects.get(content_type=ct, object_id=self.pk)
            return readnum.read_num
        except exceptions.ObjectDoesNotExist:
            return 0

class ReadDetail(models.Model):
    """
    统计每个模型对应数据的每日阅读量
    """
    date = models.DateField(default=timezone.now)
    read_num = models.IntegerField(default=0)

    content_type = models.ForeignKey(ContentType, on_delete=models.DO_NOTHING)  # 模型类
    object_id = models.PositiveIntegerField()  # 模型类的具体对象
    content_object = GenericForeignKey("content_type", "object_id")

blog/views.py
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import get_object_or_404, render, render_to_response
from django.db.models.fields import exceptions
from blog.models import Blog, BlogType
from django.core.paginator import Paginator
from django.conf import settings

from read_statistics.models import ReadNum
from read_statistics.utils import read_statistics_once_read


def get_blog_list_common_data(request, blogs_all_list):
    paginator = Paginator(blogs_all_list, settings.EACH_PAGE_BLOGS_NUMBER)
    page_num = request.GET.get("page", 1)
    page_of_blogs = paginator.get_page(page_num)  # 如果page不是数字字符会自动返回第一页
    current_page_num = page_of_blogs.number
    # 获取当前页码前后各两页的页码范围
    page_range = list(range(max(current_page_num - 2, 1), current_page_num)) + \
                 list(range(current_page_num, min((paginator.num_pages, current_page_num + 2)) + 1))
    # 加上省略号
    if page_range[0] - 1 >= 2:
        page_range.insert(0, '...')
    if page_range[-1] <= paginator.num_pages - 2:
        page_range.append('...')
    # 加上首尾页码
    if page_range[0] != 1:
        page_range.insert(0, 1)
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)
    blog_dates = Blog.objects.dates('created_time', 'day', order='DESC')
    # 获取日期分类的数量
    blog_dates_dict = {}
    for blog_date in blog_dates:
        blog_count = Blog.objects.filter(created_time__year=blog_date.year,
                                         created_time__month=blog_date.month,
                                         created_time__day=blog_date.day,
                                         ).count()
        blog_dates_dict[blog_date] = blog_count
    context = {}
    context["page_of_blogs"] = page_of_blogs  # 将获取页面对象返回前端
    context["page_range"] = page_range  # 分页显示的页码范围
    context["blog_types"] = BlogType.objects.all()
    context["blog_dates"] = blog_dates_dict
    return context


def blog_list(request):
    # 获取页码参数
    blogs_all_list = Blog.objects.all()
    context = get_blog_list_common_data(request, blogs_all_list)
    return render(request, "blog/blog_list.html", context)


def blogs_with_type(request, blog_type_pk):
    # 获取页码参数
    blog_type = get_object_or_404(BlogType, pk=blog_type_pk)
    blogs_all_list = Blog.objects.filter(blog_type=blog_type)
    context = get_blog_list_common_data(request, blogs_all_list)
    context["blog_type"] = blog_type
    return render(request, "blog/blogs_with_type.html", context)


def blogs_with_date(request, year, month, day):
    blogs_all_list = Blog.objects.filter(created_time__year=year, created_time__month=month, created_time__day=day)
    context = get_blog_list_common_data(request, blogs_all_list)
    context["blogs_with_date"] = "%s年%s月%s日" % (year, month, day)
    return render(request, "blog/blogs_with_date.html", context)


def blog_detail(request, blog_pk):
    context = {}
    blog = get_object_or_404(Blog, pk=blog_pk)
    read_cookie_key = read_statistics_once_read(request,blog)  # 调用方法为博客阅读计数，得到此博客的阅读cookie
    context["blog"] = blog
    context["previous_blog"] = Blog.objects.filter(created_time__gt=blog.created_time).last()
    context["next_blog"] = Blog.objects.filter(created_time__lt=blog.created_time).first()
    context["blog_dates"] = Blog.objects.dates('created_time', 'day', order='DESC')
    response = render_to_response("blog/blog_detail.html", context)
    response.set_cookie(read_cookie_key, "true")
    return response

mysite/views.py
from django.shortcuts import render
from django.contrib.contenttypes.models import ContentType

from blog.models import Blog
from read_statistics.utils import get_weekly_days_read_data

def home(request):
    """
    获取近一周的阅读数量，以图表的形式显示在首页
    :param request:
    :return:
    """
    blog_content_type = ContentType.objects.get_for_model(Blog)
    read_nums,dates = get_weekly_days_read_data(blog_content_type)
    context={}
    context["read_nums"]=read_nums
    context["dates"]=dates
    return render(request,"home.html",context)

read_statistics/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    {{ blog_type.title }}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/blog/blog.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <h3>{{ blog.title }}</h3>
                <ul class="blog_info_detail">
                    <li>作者：{{ blog.author }}</li>
                    <li>分类：
                        <a href="{% url 'blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a>
                    </li>
                    <li>发表日期：{{ blog.created_time|date:"Y-m-d H:i:s" }}</li>
                    <li>阅读({{ blog.get_read_num }})</li>
                </ul>
                <div class="blog_content">{{ blog.content|safe }}</div>
                <div class="blog-more">
                    {% if previous_blog %}
                        <p>上一篇：<a href="{% url 'blog_detail' previous_blog.pk %}">{{ previous_blog.title }}</a></p>
                    {% endif %}
                    {% if next_blog %}
                        <p>下一篇：<a href="{% url 'blog_detail' next_blog.pk %}">{{ next_blog.title }}</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    {{ blog_type.title }}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/blog/blog.css' %}">
{% endblock %}

{% block nav_blog_active %}active{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-9 col-lg-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% block blog_list_title %}
                        博客列表
                        {% endblock %}
                    </div>
                    <div class="panel-body">
                        {% for blog in page_of_blogs.object_list  %}
                        <div class="blog">
                            <a href="{% url 'blog_detail' blog_pk=blog.pk %}">
                                <h3>{{ blog.title }}</h3>
                            </a>
                            <p class="blog-info">
                                <span class="glyphicon glyphicon-tag" aria-hidden="true"></span><a href="{% url 'blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a>&nbsp;&nbsp;
                                <span class="glyphicon glyphicon-time" aria-hidden="true"></span>{{ blog.created_time|date:'Y-m-d' }}&nbsp;&nbsp;阅读({{ blog.get_read_num }})
                            </p>
                            <p>{{ blog.content|safe|truncatechars:120 }}</p>
                        </div>
                            {% empty %}
                        <div class="blog">
                            <h3>暂无博客，敬请期待</h3>
                        </div>
                    {% endfor %}
                    </div>
                </div>
                <div class="paginator">
                    <ul class="pagination">
                        {# 上一页 #}
                        {% if page_of_blogs.has_previous %}
                            <li>
                                <a href="?page={{ page_of_blogs.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <span aria-hidden="true">&laquo;</span>
                            </li>
                        {% endif %}
                        {# 全部页码 #}
                        {% for page_num in page_range %}
                            {% if page_num == page_of_blogs.number %}
                            <li class="active"><span>{{ page_num }}</span></li>
                            {% else %}
                                {% if page_num == '...' %}
                                    <li class="disabled"><span>{{ page_num }}</span></li>
                                {% else %}
                                    <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}

                        {# 下一页 #}
                        {% if page_of_blogs.has_next %}
                            <li>
                                <a href="?page={{ page_of_blogs.next_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <span aria-hidden="true">&raquo;</span>
                            </li>
                        {% endif %}
                    </ul>
                    <p>
                        共有{{ page_of_blogs.paginator.count }}篇博客,
                        当前第{{ page_of_blogs.number }}页,
                        共有{{ page_of_blogs.paginator.num_pages }}页
                    </p>
                </div>
            </div>
            <div class=" hidden-xs col-sm-4 col-md-3 col-lg-2">
                <div class="panel panel-default">
                    <div class="panel-heading">博客分类</div>
                    <div class="panel-body">
                        <ul class="type_list">
                            {% for blog_type in blog_types %}
                                <li>
                                    <a href="{% url 'blogs_with_type' blog_type.pk %}">
                                        {{ blog_type.title }}({{blog_type.blog_set.all|length}})
                                    </a>
                                </li>
                            {% empty %}
                                <li>暂无分类</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">日期归档</div>
                    <div class="panel-body">
                        <ul class="date_list">
                            {% for blog_date, blog_count in blog_dates.items %}
                                <li>
                                    <a href="{% url 'blogs_with_date' blog_date.year blog_date.month blog_date.day %}">
                                        {{ blog_date|date:'Y年m月d日' }}({{ blog_count }})
                                    </a>
                                </li>
                            {% empty %}
                                <li>暂无相关</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blogs_with_date.html
{% extends 'blog/blog_list.html' %}

{% block title %}
    {{ blog_type.title }}
{% endblock %}

{% block blog_list_title %}
日期归档:{{ blogs_with_date }}<a href="{% url 'blog_list' %}"> 查看全部博客</a>
{% endblock %}

blog/templates/blog/blogs_with_type.html
{% extends 'blog/blog_list.html' %}

{% block title %}
    {{ blog_type.title }}
{% endblock %}

{% block blog_list_title %}
分类:{{ blog_type.title }}<a href="{% url 'blog_list' %}"> 查看全部博客</a>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Comptible" content="IE=EDGE">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'jquery1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    {% block css %}
    {% endblock %}
</head>
<body>

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="{% url 'home' %}" class="navbar-brand">个人博客网站</a>
            <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar-collapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="{% block nav_home_active %}{% endblock %}"><a href="{% url 'home' %}">首页</a></li>
                <li class="{% block nav_blog_active %}{% endblock %}"><a href="{% url 'blog_list' %}">博客列表</a></li>
            </ul>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}


</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
我的网站|首页
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
{% endblock %}

{% block nav_home_active %}active{% endblock %}
{% block content %}
<h3 class="home_content">Welcome Everyone，xixixixi......</h3>
<!-- 图表容器 DOM -->
<div id="container"></div>
<!-- 引入 highcharts.js -->
<script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
<script>
        // 图表配置
        var options = {
            chart: { type: 'line' },//指定图表的类型，默认是折线图（line）
            title: { text: null },   // 标题
            xAxis: {
                categories: {{ dates|safe }},   // x 轴分类
                tickMarkPlacement:"on",
            },

            yAxis: {
                title: {
                    text: null                // y 轴标题
                },
                labels:{enabled: false},
                gridLineDashStyle:"Dash",
            },
            series: [{                              // 数据列
                name: '阅读量',                        // 数据列名
                data: {{ read_nums }}                     // 数据
            }],
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend:{ enabled: false },
            credits:{ enabled: false },
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);

</script>
{% endblock %}